### ISSUE TITLE
Create a list showing where all of the metadata documentation is currently found.

### ISSUE THREAD

**Issue by karenmajewicz** [geoblacklight/geoblacklight-metadata#11]

**Comment by rmseifried** [comment]
I created a Google Doc with information about the places on the web where metadata documentation lives, and space to brainstorm how we want to move forward with consolidating the information:

[GeoBlacklight metadata documentation locations](https://docs.google.com/document/d/191QXbeX7W_ePKKHVZyxRcG3eV7uKTLEe90sDHjyj4Po/edit?usp=sharing)

**Comment by karenmajewicz** [comment]
Great work!
