### ISSUE TITLE
Link the new OGM site to the domain opengeometadata.org

### ISSUE THREAD

**Issue by rmseifried** [geoblacklight/geoblacklight-metadata#20]
The new OpenGeoMetadata site is up and running (https://github.com/OpenGeoMetadata/opengeometadata.github.io). @cbeer can you confirm we have the domain opengeometadata.org and get those connected?

**Comment by karenmajewicz** [comment]
Hi @thatbudakguy Is this something you could find out for us?

**Comment by thatbudakguy** [comment]
I've confirmed that SUL owns opengeometadata.org and requested that it be pointed at https://opengeometadata.github.io/.

**Comment by thatbudakguy** [comment]
@karenmajewicz could you try hitting "check again"? i think now we need to create a CNAME file that lives in https://github.com/OpenGeoMetadata/opengeometadata.github.io, which github should prompt you to do. you may need to hit "remove" and re-enter opengeometadata.org in the box above, not sure.

**Comment by karenmajewicz** [comment]
I am trying now. Seeing the message: _TLS certificate is being provisioned. This may take up to 15 minutes to complete._

**Comment by karenmajewicz** [comment]
It is working! We are official: https://opengeometadata.org

Thanks @thatbudakguy
