### ISSUE TITLE
Create a new field for spatial envelopes

### ISSUE THREAD

**Issue by karenmajewicz** [geoblacklight/geoblacklight-metadata#25]
This field will be needed for spatial relevancy searching and can only be a rectangular bounding box in the ENVELOPE() format.

**Comment by karenmajewicz** [comment]
See https://github.com/geoblacklight/geoblacklight/issues/1158

**Comment by rmseifried** [comment]
Per https://github.com/geoblacklight/geoblacklight/issues/1158, the decision is to name the field `dcat_bbox` based on the [dcat specification](https://www.w3.org/TR/vocab-dcat-2/#Property:location_bbox) with a required format of `"ENVELOPE(-79.750232,-71.750494,44.999963,40.499893)"`

**Comment by karenmajewicz** [comment]
With the addition of the 3rd field, I wonder if we want to update the application's label for Spatial Extent. Since this is now a complex geometry field, maybe that label is not accurate.  Here is the simplest option:

1. geometry `locn_geometry`
2. bbox `dcat_bbox`
3. centroid `dcat_centroid`

**Comment by rmseifried** [comment]
This makes sense to me. Perhaps "Bounding Box" or "Envelope" instead of "Bbox"?

**Comment by karenmajewicz** [comment]
Done see (https://opengeometadata.org/docs/aardvarkSchema/bounding-box/)
