### ISSUE TITLE
Rename dcat_centroid_ss to dcat_centroid

### ISSUE THREAD

**Issue by rmseifried** [geoblacklight/geoblacklight-metadata#26]
See PR https://github.com/geoblacklight/geoblacklight/pull/1159

Per discussion about the new spatial field `dcat_bbox`  (#25) we decided to bring all 3 location fields into alignment with the [w3 location fields](https://www.w3.org/TR/vocab-dcat-2/#Class:Location) by not including suffixes. 

The field `dcat_centroid_ss` should be renamed to `dcat_centroid`.

**Comment by karenmajewicz** [comment]
Done see https://opengeometadata.org/docs/aardvarkSchema/centroid/
