### ISSUE TITLE
Get an SSL certificate for opengeometadata.org

### ISSUE THREAD

**Issue by rmseifried** [geoblacklight/geoblacklight-metadata#29]
Opengeometadata.org is pointing to HTTP, not HTTPS. @thatbudakguy can we get an SSL certificate for the site?

![image](https://user-images.githubusercontent.com/36506059/155158847-792a99bd-faa3-4d9e-83ff-52697304a504.png)

**Comment by thatbudakguy** [comment]
could someone with admin permissions for the repo try following [these instructions for enforcing HTTPS](https://docs.github.com/en/pages/getting-started-with-github-pages/securing-your-github-pages-site-with-https#enforcing-https-for-your-github-pages-site)? GitHub should be able to request a cert for you via LetsEncrypt. let me know if this doesn't work.

**Comment by karenmajewicz** [comment]
That worked Nick. Thanks!
