### ISSUE TITLE
Fix image links on Transform Metadata page

### ISSUE THREAD

**Issue by rmseifried** [geoblacklight/geoblacklight-metadata#37]
The links on this page correctly point to the new image locations (e.g. https://github.com/OpenGeoMetadata/opengeometadata.github.io/blob/main/assets/images/ISO_snippet.png) but are not displaying on the website.

**Comment by karenmajewicz** [comment]
Fixed in this PR https://github.com/OpenGeoMetadata/metadata-issues/issues/37

The links need to be relative, so I changed them from something like https://github.com/OpenGeoMetadata/opengeometadata.github.io/blob/main/assets/images/ISO_snippet.png to `/..assets/images/ISO_snippet.png`
