### ISSUE TITLE
Update references to 1.0 to aardvark schema scripts

### ISSUE THREAD

**Issue by karenmajewicz** [geoblacklight/geoblacklight-metadata#38]
https://github.com/mjanowiecki/geoportal/tree/main/aardvark

**Comment by rmseifried** [comment]
There is also a GeoCombine branch in the works: https://github.com/OpenGeoMetadata/GeoCombine/tree/121-migrate-to-aardvark

**Comment by rmseifried** [comment]
Right now scripts are being referenced in two places on the website:
* At the bottom of the [upgrade guide](https://opengeometadata.org/docs/current-schema/upgrading/#tools-and-techniques-for-upgrading)
* The dedicated [scripts and tools page](https://opengeometadata.org/docs/helpful-resources/scripts-and-tools/)

I'd recommend moving all scripts and tools to that dedicated page, and replacing the content on the upgrade guide with a link to that page.

**Comment by karenmajewicz** [comment]
Added missing link to https://github.com/mjanowiecki/geoportal/tree/main/aardvark
