### ISSUE TITLE
Add info to GBL 1.0 and crosswalks about discrepancy between publisher as single or multivalued

### ISSUE THREAD

**Issue by karenmajewicz** [geoblacklight/geoblacklight-metadata#45]
In GBL 1.0, the publisher field has variously been used as `dc_publisher_s` or `dc_publisher_sm`. The most common was the single-value, which is what our documentation states. However, OpenGeoMetadata repositories may contain both fields and this will affect transformations.

**Comment by karenmajewicz** [comment]
We reviewed and this is described in the Publisher field. Are there other places this is still showing in conflict?

**Comment by rmseifried** [comment]
@karenmajewicz can you reach out to the person who flagged this as an issue and ask for specifics about where they encountered the discrepancy?

**Comment by karenmajewicz** [comment]
This was only present in old documentation, which has since be removed.
